apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: lab-agent
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: changeme-mongo
  REDIS_PASSWORD: changeme-redis
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: changeme-rabbitmq
